### ISSUE TITLE
I get this error when trying to execute the gcc-buld script

### ISSUE THREAD

**Issue by aliquo93** [slyfox1186/script-repo#8] opened 2024-02-01 02:43 UTC
```
Building pkg-config - version 0.29.2
======================================
Downloading "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz" saving as "pkg-config-0.29.2.tar.gz"
Download Completed
File extracted: pkg-config-0.29.2.tar.gz

$ ./configure --prefix=/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace --with-pc-path=/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib64/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/share/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib/x86_64-linux-gnu/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/usr/lib/pkgconfig:/lib64/pkgconfig:/lib/pkgconfig:/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/mit-krb5:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/share/pkgconfig:/usr/share/pkgconfig


Failed to execute: ./configure --prefix=/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace --with-pc-path=/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib64/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/share/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/lib/x86_64-linux-gnu/pkgconfig:/home/daniele/Documenti/Latte_Layouts/script-repo-main/Bash/Installer Scripts/GNU Software/gcc-build-script/workspace/usr/lib/pkgconfig:/lib64/pkgconfig:/lib/pkgconfig:/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/mit-krb5:/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/share/pkgconfig:/usr/share/pkgconfig. Line: 332

If you want help fixing a bug, create a support ticket!

https://github.com/slyfox1186/script-repo/issues
```

**Comment by slyfox1186** [comment] 2024-02-23 06:04
I tried to reproduce this on Debian 12 and Ubuntu Jammy and I could not.

It appears that one possible cause is you have variables overlapping that have been set somehow before the script was ever run. Check what variables you have set using the `set` command.

Also, execute the script with the command `set -x` above the pkg-config build command and paste the output in terminal here for me to review.

Sorry it took me a while to get back to you but I will try to help you the best I can.

**Comment by thestormbreaker** [comment] 2024-02-24 18:43
Ubuntu 22.04.04
------------------------------
Choose the GCC version(s) to install
======================================

[1] All
[2] GCC 10
[3] GCC 11
[4] GCC 12
[5] GCC 13

Your choices are (1 to 5): 5

Building gcc-13 - version 13.2.0
======================================
The file "gcc-13.2.0.tar.xz" is already downloaded.
File extracted: gcc-13.2.0.tar.xz

$ autoreconf -fi
$ ./contrib/download_prerequisites
$ ../configure --prefix=/usr/local --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --disable-assembly --disable-nls --disable-vtable-verify --disable-werror --enable-bootstrap --enable-cet --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-gnu-unique-object --enable-languages=c,ada,c++,d,fortran,go,lto,m2,objc,obj-c++ --enable-libphobos-checking=release --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-linker-build-id --enable-link-serialization=2 --enable-lto --enable-multiarch --enable-multilib --enable-offload-defaulted --enable-offload-targets=nvptx-none=/build/gcc-13-aYYs71/gcc-13-13.2.0/debian/tmp-nvptx/usr/local,amdgcn-amdhsa=/build/gcc-13-aYYs71/gcc-13-13.2.0/debian/tmp-gcn/usr/local --enable-plugin --enable-shared --enable-threads=posix --libdir=/usr/local/lib --libexecdir=/usr/local/libexec --program-prefix=x86_64-linux-gnu- --program-suffix=-13 --with-abi=m64 --with-arch-32=i686 --with-build-config=bootstrap-lto-lean --with-default-libstdcxx-abi=new --with-gcc-major-version-only --with-isl=/usr --with-libiconv-prefix=/usr --with-link-serialization=2 --with-multilib-list=m32,m64,mx32 --with-pkgversion=Ubuntu 13.2.0 --with-system-zlib --with-target-system-zlib=auto --with-tune=generic --with-zstd=/home/storm/5.4/build-enviroment/builds/gcc-build-script/workspace --without-included-gettext --with-cuda-driver

$ Compiling gcc-13 with languages=c,ada,c++,d,fortran,go,lto,m2,objc,obj-c++}
$ This is going to take a while...

$ make -j12
The given address is empty


Failed to execute: make -j12. Line: 291

**Comment by slyfox1186** [comment] 2024-03-17 07:08
Since there has been no updates I am closing this issue. Re-open if necessary.

**Closed by slyfox1186** 2024-03-17 07:08 UTC
